# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "thread",
  "person",
  "post",
  "session",
  "antibot"
]

const attributes = [
  Attr(name: "id", tabIndex: 0, typ: dbInt, key: 1),
  Attr(name: "name", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "views", tabIndex: 0, typ: dbInt, key: 0),
  Attr(name: "modified", tabIndex: 0, typ: dbTimestamp, key: 0),
  Attr(name: "id", tabIndex: 1, typ: dbInt, key: 1),
  Attr(name: "name", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "password", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "email", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "creation", tabIndex: 1, typ: dbTimestamp, key: 0),
  Attr(name: "salt", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "status", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "lastonline", tabIndex: 1, typ: dbTimestamp, key: 0),
  Attr(name: "ban", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "id", tabIndex: 2, typ: dbInt, key: 1),
  Attr(name: "author", tabIndex: 2, typ: dbInt, key: -5),
  Attr(name: "ip", tabIndex: 2, typ: dbVarchar, key: 0),
  Attr(name: "header", tabIndex: 2, typ: dbVarchar, key: 0),
  Attr(name: "content", tabIndex: 2, typ: dbVarchar, key: 0),
  Attr(name: "thread", tabIndex: 2, typ: dbInt, key: -1),
  Attr(name: "creation", tabIndex: 2, typ: dbTimestamp, key: 0),
  Attr(name: "id", tabIndex: 3, typ: dbInt, key: 1),
  Attr(name: "ip", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "password", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "userid", tabIndex: 3, typ: dbInt, key: -5),
  Attr(name: "lastmodified", tabIndex: 3, typ: dbTimestamp, key: 0),
  Attr(name: "id", tabIndex: 4, typ: dbInt, key: 1),
  Attr(name: "ip", tabIndex: 4, typ: dbVarchar, key: 0),
  Attr(name: "answer", tabIndex: 4, typ: dbVarchar, key: 0),
  Attr(name: "created", tabIndex: 4, typ: dbTimestamp, key: 0)
]
