# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "tb_serial",
  "tb_boolean",
  "tb_float",
  "tb_string",
  "tb_timestamp",
  "tb_json"
]

const attributes = [
  Attr(name: "typserial", tabIndex: 0, typ: dbInt, key: 1),
  Attr(name: "typinteger", tabIndex: 0, typ: dbInt, key: 0),
  Attr(name: "typboolean", tabIndex: 1, typ: dbBool, key: 0),
  Attr(name: "typfloat", tabIndex: 2, typ: dbFloat, key: 0),
  Attr(name: "typstring", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "dt1", tabIndex: 4, typ: dbTimestamp, key: 0),
  Attr(name: "dt2", tabIndex: 4, typ: dbTimestamp, key: 0),
  Attr(name: "typjson", tabIndex: 5, typ: dbJson, key: 0)
]
